#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 02 00:45:22 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=ComplementaryUnbound_r5.7.1.zip
