State:9
Info:Acadia's Veil-fabric-1.20.1-0.0.1
Logo:PCL\Logo.png
ReleaseTime:2023-06-12 21:25
VersionFabric:0.19.2
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionVanillaName:1.20.1
VersionVanilla:20.0.1
VersionArgumentIndieV2:True
LogoCustom:True
CustomInfo:Acadia's Veil-fabric-1.20.1-0.0.1
VersionArgumentTitle:阿卡狄亚之纱
VersionArgumentInfo:Acadia‘s Veil-fabric-1.20.1-0.0.1
VersionRamType:0
VersionRamOptimize:1
VersionAdvanceGC:5
VersionRamCustom:26
VersionAdvanceJava:True
VersionAdvanceDisableModUpdate:True
VersionAdvanceDisableLUA:True
VersionAdvanceDisableJLW:True
IsStar:False
