#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Tue Apr 28 06:08:40 CST 2026
alwaysLogTamperWarnings=true
